apiVersion: v1
kind: Service
metadata:
  name: api-s # Nombre del servicio
  namespace: default
  labels:
    app: api
spec:
  selector:
    app: api
  type: NodePort  # Tipo de servicio
  ports:
  - name: http-port
    protocol: TCP
    port: 80  # Puerto expuesto en el servicio
    targetPort: 80  # Puerto expuesto en el contenedor
    nodePort: 30580  # Para acceder desde el exterior (en el rango 30000-32767)